CREATE DATABASE IF NOT EXISTS file_storage;

USE file_storage;

CREATE TABLE IF NOT EXISTS file_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image LONGBLOB,
    pdf LONGBLOB
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);