FROM python:3.12.3-slim

WORKDIR /app

# Copy application code
COPY ./app /app

# Create a virtual environment in the .venv directory
RUN python -m venv /app/.venv

# Install dependencies within the virtual environment
RUN /app/.venv/bin/pip install -r requirements.txt

# Set environment variables for Python to use the virtual environment
ENV PATH="/app/.venv/bin:$PATH"

# Run the script to add data to MySQL
RUN /app/.venv/bin/python /app/addDataToMySQL.py

# Run the FastAPI application on port 8080
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
